# version: '3.8'

# services:
#   mysql:
#     image: mysql:8.0
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: sensor_data
#       MYSQL_USER: app_user
#       MYSQL_PASSWORD: app_password
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql
#       - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#     networks:
#       - app_network
#     healthcheck:
#       test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#       timeout: 20s
#       retries: 10

#   fastapi:
#     build: .
#     container_name: fastapi_app
#     restart: always
#     ports:
#       - "8000:8000"
#     environment:
#       MYSQL_USER: root
#       MYSQL_PASSWORD: password
#       MYSQL_HOST: mysql
#       MYSQL_PORT: 3306
#       MYSQL_DATABASE: sensor_data
#     depends_on:
#       mysql:
#         condition: service_healthy
#     volumes:
#       - ./uploads:/app/uploads
#     networks:
#       - app_network

# volumes:
#   mysql_data:

# networks:
#   app_network:
#     driver: bridge
version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db1
    restart: always
    command: --max_allowed_packet=67108864 --innodb_buffer_pool_size=268435456
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: sensor_data
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  fastapi:
    build: .
    container_name: fastapi_app1
    restart: always
    ports:
      - "8001:8000"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql_db1
      MYSQL_PORT: 3306
      MYSQL_DATABASE: sensor_data
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge